version: '3.3'

services:

  react:
    image: auction-app
    build: ./frontend
    links: 
      - api
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules/     
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=1000
  api:
    ports:
      - "3002:3002"
    volumes:
      - ./backend:/usr/src/app/
      - /usr/src/app/node_modules/
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=1000
  mongo:
    restart: always
    ports:
      - "27017:27017"
  mongo-express:
    restart: always
    ports:
      - 8081:8081